### ISSUE TITLE
Deprecations version 2.0

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1125]
- [x] N6 collector rename: remove compatibility module (see #1124)
- [x] ~~Backwards compatibility on extra field with type JSON (see #1046)~~ -> postponed to 3.0.0, see #1404 
- [x] compatibility shim `bots.parsers.cymru_full_bogons.parser`
- [x] parameter rename `feed` to `name` in collectors.
- [x] `intelmq.lib.pipeline.Pipeline.sleep`
- [x] `bots.experts.ripencc_abuse_contact`: parameter `query_ripe_stat` (#1291)
- [x] `lib.utils`: `extract_tar`

**Comment by wagner-certat** [comment]
- [ ] Backwards compatibility on extra field with type JSON.

**Comment by wagner-certat** [comment]
- [ ] compatibility shim `bots.parsers.cymru_full_bogons.parser`
- [ ] parameter rename `feed` to `name` in collectors.

**Comment by wagner-certat** [comment]
- [ ] `intelmq.lib.pipeline.Pipeline.sleep`

**Comment by wagner-certat** [comment]
`bots.experts.ripencc_abuse_contact`: parameter `query_ripe_stat` (#1291)

**Comment by wagner-certat** [comment]
`lib.utils`: `extract_tar`

**Comment by wagner-certat** [comment]
484ee09e41d691d241854a20307c68a550357162
