### ISSUE TITLE
mismatch of our types with upstream RSIT

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1409]
There are a couple of types which are not in RSIT. What to do with them?

 - [ ] information content security > dropzone: asked on RSIT ML for input -> PR #2006 
 - [x] information content security > leak: data-leak https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/61
 - [X] intrusions > backdoor: merged into system-compromise in PR #1995
 - [x] intrusions > compromised: replace by system-compromise https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/59 -> PR #1993
 - [x] intrusions > defacement: replace by unauthorised-information-modification and a specific identifier https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/73 -> PR #1994
 - [x] intrusions > unauthorized-command not accepted upstream: https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/49 replacement system-compromise: https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/59  -> PR #1993
 - [x] intrusions > unauthorized-login not accepted upstream: https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/49 replacement system-compromise: https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/59  -> PR #1993
 - [x] malicious code > dga domain: ~https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/32~ Rejected by RSIT, see #1613; replace by other > dga-domain -> PR #1992
 - [x] malicious code > malware: replace by infected-system or malware-distribution, PR #1917 
 - [x] malicious code > ransomware: replace by infected-system
 - [x] other > proxy: Other can deviate from RSIT
 - [x] other > tor: Other can deviate from RSIT
 - [x] other > unknown: different name https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/46
 - [x] vulnerable > vulnerable client: vulnerable-system
 - [x] vulnerable > vulnerable service: vulnerable-system
 - [x] `information content security` -> `information-content-security` (taxonomy expert)

https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force

cc @aaronkaplan @th-certbund
